apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    # Le serveur officiel de Let's Encrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    email: morgan.mabille@apprenant.ifapme.be
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: traefik
