---
- name: Préparer le serveur, installer K3S et déployer l'App
  hosts: web
  become: true
  tasks:
#On récupère l'ID du code
    - name: Récupérer le Short SHA localement depuis Git
      local_action: command git rev-parse --short HEAD
      register: git_sha
      become: false
      changed_when: false

#On attend que le système AWS soit prêt
    - name: Attendre le déverrouillage de APT (Sécurité AWS)
      raw: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done;

    - name: Mettre à jour le cache APT et les paquets
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installer curl
      apt:
        name: curl
        state: present

    - name: Installer K3s
      shell: curl -sfL https://get.k3s.io | sh -
      args:
        creates: /usr/local/bin/k3s

    - name: Créer un dossier pour les manifestes K8s
      file:
        path: /home/ubuntu/k8s-manifests
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Installer Cert-Manager sur Kubernetes
      shell: k3s kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml

    - name: Attendre que Cert-Manager soit prêt (environ 30-60s)
      shell: k3s kubectl wait --for=condition=Available deployment --all -n cert-manager --timeout=300s

    - name: Copier les fichiers de déploiement et de service
      copy:
        src: "../k8s/{{ item }}"
        dest: "/home/ubuntu/k8s-manifests/{{ item }}"
      loop:
        - deployment.yaml
        - service.yaml
        - ingress.yaml
        - cluster-issuer.yaml

#On injecte la version dynamique
    - name: Injecter la bonne version de l'image dans le manifeste
      replace:
        path: /home/ubuntu/k8s-manifests/deployment.yaml
        regexp: '__VERSION__'
        replace: "{{ git_sha.stdout }}"

    - name: Appliquer les manifestes Kubernetes
      shell: k3s kubectl apply -f /home/ubuntu/k8s-manifests/
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
